### ISSUE TITLE
Make MAC address permanent

### ISSUE THREAD

**Issue by randlor** [halmartin/meraki-builder#10]
Currently the MAC address is dynamically generated on boot, resulting in a constantly changing (or incrementing) IP address when using DHCP.  It also means DHCP address associations are not possible in router configs etc. 

It should be possible to set the MAC address on initial boot after flash, rather than dynamically generating each boot.  

Please assign this to me.

**Comment by halmartin** [comment]
Behaviour changed to default the random MAC address generated on first boot: ded4e19c737e6a538ff819518f1099258bb2de4c

If you want to change this to the MAC address of your device, simply edit `/etc/MERAKI_MAC` and reboot.

**Comment by halmartin** [comment]
On second thought, there is an AT25 EEPROM present in these switches that contains the Meraki MAC address. We should just read the factory MAC address from that. I'll look into how best to accomplish this.
