### ISSUE TITLE
UART pinout for MS22P?

### ISSUE THREAD

**Issue by networkdawg** [halmartin/meraki-builder#14]
I opened up my MS22P switch yesterday, and am trying to figure out the jumper layout for it. I suspect J3 is the UART pins, but looking for confirmation as I didn't get any serial response from it.

**Comment by halmartin** [comment]
You're the first person (that I'm aware of) to try this on an MS22P. I don't know the UART pins. Are you able to email me (or imgur) high resolution photos of the PCB?

**Comment by networkdawg** [comment]
@halmartin I have uploaded a bunch to Google Photos. https://photos.app.goo.gl/ngTeMSfBnakoKgW16

I suspect it is J3, however I discovered the pin that I believe is GND, has no solder holding it to the board, so the pin just pushes through. I am going to tack on a small dab of solder and see if I can get any serial response then.

**Comment by halmartin** [comment]
I would guess UART is J4, on the left side of the board.

You should confirm with a multimeter that none of the pins of J4 have greater than 3.3V present (with the switch powered on) and then connect a UART adapter with the usual pinout:

1. VCC (no connection)
1. Uart Tx
1. Uart Rx
1. GND

**Do not** use the resistance/connectivity test on your meter, as you will damage the SoC!

Please also be careful when measuring, as J4 appears to be near the PoE injection board, which carries 57VDC. For added safety, you should disconnect the PoE power cable (blue/black) while probing J4.

For testing J3, you can just unplug one of the fans and use the ground pin of the fan for your UART connection.

JY1 and JY2 probably map to the pins of the SOIC16, as the MS22 has a PCB layout similar to the MS42. In that case, pin 1 of JY1 may be GND.

**Comment by networkdawg** [comment]
@halmartin  you were correct. UART is J4. GND is the pin closest to the front of the switch. I have the bootlog for it.

LinuxLoader built Nov 12 2014 18:01:50
init_pll ok
init_spi ok
init_memctl ok
wait_memctl ok
Training DRAM ok
init_irq ok
init_dram_uncached ok
init_icache ok
init_dcache ok
enable_caches ok
init_board ok
Low level initialization complete, exiting boot mode
[    0.000000] Linux version 2.6.32.62-meraki-elemental (jimroewe@jimroewe-linux) (gcc version 4.7.1 (GCC) ) #1 Thu Dec 11 11:28:32 PST 2014
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 02019654 (MIPS 24Kc)
[    0.000000] Determined physical RAM map:
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 07ff0000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone PFN ranges:
[    0.000000]   Normal   0x00000000 -> 0x00007ff0
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00000000 -> 0x00007ff0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32496
[    0.000000] Kernel command line: console=ttyS0,115200 mtdparts=m25p80:0x40000(loader1),0x3c0000(boot1),0x40000(loader2),0x3c0000(boot2),0x80000(rsvd),0x600000(bootubi),0x40000(conf),0x100000(stackconf),0x40000(syslog) ubi.mtd=bootubi ubi.mtd=gen_nand.0 mem=134152192
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Writing ErrCtl register=80000002
[    0.000000] Readback ErrCtl register=80000002
[    0.000000] Cache parity protection enabled
[    0.000000] Memory: 124928k/131008k available (2117k kernel code, 5904k reserved, 574k data, 956k init, 0k highmem)
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:66
[    0.001000] Calibrating delay loop... 277.50 BogoMIPS (lpj=138752)
[    0.023000] Mount-cache hash table entries: 512
[    0.026000] devtmpfs: initialized
[    0.029000] NET: Registered protocol family 16
[    0.045000] bio: create slab <bio-0> at 0
[    0.049000] Switching to clocksource MIPS
[    0.056000] NET: Registered protocol family 2
[    0.061000] IP route cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.068000] TCP established hash table entries: 4096 (order: 3, 32768 bytes)
[    0.075000] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.082000] TCP: Hash tables configured (established 4096 bind 4096)
[    0.088000] TCP reno registered
[    0.092000] NET: Registered protocol family 1
[    0.126000] VCORE-III Watchdog Timer enabled (30 seconds).  Prev boot was not caused by WDT reset.
[    0.139000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.145000] Registering unionfs 2.5.10 (for 2.6.32.46)
[    0.150000] msgmni has been set to 244
[    0.168000] io scheduler noop registered
[    0.172000] io scheduler deadline registered (default)
[    0.179000] Trying to register dev faulty etc
[    0.185000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.194000] serial8250.0: ttyS0 at MMIO 0x70100000 (irq = 14) is a 16550A
[    0.201000] console [ttyS0] enabled, bootconsole disabled
[    0.201000] console [ttyS0] enabled, bootconsole disabled
[    0.214000] m25p80 spi0.1: found mx25l12805d, expected m25p80
[    0.220000] m25p80 spi0.1: mx25l12805d (16384 Kbytes)
[    0.225000] 9 cmdlinepart partitions found on MTD device m25p80
[    0.231000] Creating 9 MTD partitions on "m25p80":
[    0.236000] 0x000000000000-0x000000040000 : "loader1"
[    0.245000] 0x000000040000-0x000000400000 : "boot1"
[    0.254000] 0x000000400000-0x000000440000 : "loader2"
[    0.263000] 0x000000440000-0x000000800000 : "boot2"
[    0.272000] 0x000000800000-0x000000880000 : "rsvd"
[    0.281000] 0x000000880000-0x000000e80000 : "bootubi"
[    0.290000] 0x000000e80000-0x000000ec0000 : "conf"
[    0.299000] 0x000000ec0000-0x000000fc0000 : "stackconf"
[    0.309000] 0x000000fc0000-0x000001000000 : "syslog"
[    0.319000] ONFI flash detected
[    0.323000] ONFI param page 0 valid
[    0.326000] NAND device: Manufacturer ID: 0x2c, Chip ID: 0xf1 (Micron MT29F1G08ABADAWP)
[    0.339000] Scanning device for bad blocks
[    0.451000] UBI: attaching mtd5 to ubi0
[    0.455000] UBI: physical eraseblock size:   4096 bytes (4 KiB)
[    0.461000] UBI: logical eraseblock size:    3968 bytes
[    0.466000] UBI: smallest flash I/O unit:    1
[    0.471000] UBI: VID header offset:          64 (aligned 64)
[    0.477000] UBI: data offset:                128
[    1.413000] UBI: max. sequence number:       2
[    1.453000] UBI: attached mtd5 to ubi0
[    1.457000] UBI: MTD device name:            "bootubi"
[    1.462000] UBI: MTD device size:            6 MiB
[    1.467000] UBI: number of good PEBs:        1536
[    1.472000] UBI: number of bad PEBs:         0
[    1.476000] UBI: number of corrupted PEBs:   0
[    1.480000] UBI: max. allowed volumes:       23
[    1.485000] UBI: wear-leveling threshold:    4096
[    1.490000] UBI: number of internal volumes: 1
[    1.494000] UBI: number of user volumes:     0
[    1.499000] UBI: available PEBs:             1532
[    1.504000] UBI: total number of reserved PEBs: 4
[    1.508000] UBI: number of PEBs reserved for bad PEB handling: 0
[    1.514000] UBI: max/mean erase counter: 2/1
[    1.519000] UBI: image sequence number:  -2100605408
[    1.524000] UBI: background thread "ubi_bgt0d" started, PID 147
[    1.530000] UBI: attaching mtd9 to ubi1
[    1.534000] UBI: physical eraseblock size:   131072 bytes (128 KiB)
[    1.541000] UBI: logical eraseblock size:    129024 bytes
[    1.546000] UBI: smallest flash I/O unit:    2048
[    1.551000] UBI: sub-page size:              512
[    1.556000] UBI: VID header offset:          512 (aligned 512)
[    1.562000] UBI: data offset:                2048
[    2.303000] UBI: max. sequence number:       1480550
[    2.337000] UBI: attached mtd9 to ubi1
[    2.341000] UBI: MTD device name:            "gen_nand.0"
[    2.346000] UBI: MTD device size:            128 MiB
[    2.351000] UBI: number of good PEBs:        1024
[    2.356000] UBI: number of bad PEBs:         0
[    2.361000] UBI: number of corrupted PEBs:   0
[    2.365000] UBI: max. allowed volumes:       128
[    2.370000] UBI: wear-leveling threshold:    4096
[    2.374000] UBI: number of internal volumes: 1
[    2.379000] UBI: number of user volumes:     7
[    2.383000] UBI: available PEBs:             514
[    2.388000] UBI: total number of reserved PEBs: 510
[    2.393000] UBI: number of PEBs reserved for bad PEB handling: 20
[    2.399000] UBI: max/mean erase counter: 1562/1446
[    2.404000] UBI: image sequence number:  1648387176
[    2.410000] UBI: background thread "ubi_bgt1d" started, PID 156
[    2.444000] tun: Universal TUN/TAP device driver, 1.6
[    2.449000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    2.456000] i2c /dev entries driver
[    2.463000] TCP cubic registered
[    2.467000] NET: Registered protocol family 17
[    2.471000] 802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
[    2.478000] All bugs added by David S. Miller <davem@redhat.com>
[    2.484000] Meraki MS22 or MS220-24 board detected
[    2.492000] i2c-gpio i2c-gpio.1: using pins 10 (SDA) and 11 (SCL)
[    2.500000] at24 1-0051: 8192 byte at24 EEPROM (writable)
[    2.654000] meraki-config: Failure to read from eeprom
[    2.664000] i2c-gpio: probe of i2c-gpio.2 failed with error -22
[    2.679000] devtmpfs: mounted
[    2.699000] Freeing unused kernel memory: 956k freed
[    2.706000] Made it into bootsh: Dec 11 2014 11:26:54
[    2.712000] bootsh build switch-5-150928
grep meraki-board-config /proc/misc | awk '{print $1}'
[    6.413000] Algorithmics/MIPS FPU Emulator v1.5
[    6.543000] UBIFS: recovery needed
[    6.718000] UBIFS: recovery completed
[    6.722000] UBIFS: mounted UBI device 1, volume 4, name "storage"
[    6.728000] UBIFS: file system size:   7354368 bytes (7182 KiB, 7 MiB, 57 LEBs)
[    6.736000] UBIFS: journal size:       1032193 bytes (1008 KiB, 0 MiB, 6 LEBs)
[    6.743000] UBIFS: media format:       w4/r0 (latest is w4/r0)
[    6.749000] UBIFS: default compressor: lzo
[    6.753000] UBIFS: reserved for root:  347364 bytes (339 KiB)
[    6.893000] Mapping 21028864 bytes for /dev/mtdblock/part1
[   13.206000] Ehdr.e_entry = 803228e0 Ehdr.e_phoff = 34
[   13.212000] Phdr.p_offset = 2000 phdr.p_vaddr=80100000 phdr.p_filesz=cb3f58 phdr.p_memsz=ccd858
[   13.511000] UBIFS: un-mount UBI device 1, volume 4
[   13.524000] Starting new kernel
[   13.527000] Will call new kernel at 803228e0
[   13.527000] Bye ...
[    0.000000] Linux version 2.6.32.62-meraki-elemental (meraki@buildbot104.meraki.com) (gcc version 4.7.1 (GCC) ) #2 Fri Sep 4 14:15:02 PDT 2015
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 02019654 (MIPS 24Kc)
[    0.000000] Determined physical RAM map:
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 07ff0000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone PFN ranges:
[    0.000000]   Normal   0x00000000 -> 0x00007ff0
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00000000 -> 0x00007ff0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32496
[    0.000000] Kernel command line: console=ttyS0,115200 mtdparts=m25p80:0x40000(loader1),0x3c0000(boot1),0x40000(loader2),0x3c0000(boot2),0x80000(rsvd),0x600000(bootubi),0x40000(conf),0x100000(stackconf),0x40000(syslog) ubi.mtd=bootubi ubi.mtd=gen_nand.0 mem=134152192
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Writing ErrCtl register=80000002
[    0.000000] Readback ErrCtl register=80000002
[    0.000000] Cache parity protection enabled
[    0.000000] Memory: 115556k/131008k available (2226k kernel code, 15264k reserved, 606k data, 10172k init, 0k highmem)
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:66
[    0.001000] Calibrating delay loop... 277.50 BogoMIPS (lpj=138752)
[    0.023000] Mount-cache hash table entries: 512
[    0.026000] devtmpfs: initialized
[    0.029000] NET: Registered protocol family 16
[    0.046000] bio: create slab <bio-0> at 0
[    0.052000] Switching to clocksource MIPS
[    0.059000] NET: Registered protocol family 2
[    0.064000] IP route cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.071000] TCP established hash table entries: 4096 (order: 3, 32768 bytes)
[    0.079000] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.085000] TCP: Hash tables configured (established 4096 bind 4096)
[    0.091000] TCP reno registered
[    0.095000] NET: Registered protocol family 1
[    3.283000] Algorithmics/MIPS FPU Emulator v1.5
[    3.321000] VCORE-III Watchdog Timer enabled (30 seconds).  Prev boot was not caused by WDT reset.
[    3.446000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.452000] Registering unionfs 2.5.10 (for 2.6.32.46)
[    3.489000] msgmni has been set to 226
[    3.513000] io scheduler noop registered
[    3.517000] io scheduler deadline registered (default)
[    3.525000] Trying to register dev faulty etc
[    3.543000] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    3.583000] serial8250.0: ttyS0 at MMIO 0x70100000 (irq = 14) is a 16550A
[    3.590000] console [ttyS0] enabled, bootconsole disabled
[    3.590000] console [ttyS0] enabled, bootconsole disabled
[    3.685000] m25p80 spi0.1: found mx25l12805d, expected m25p80
[    3.691000] m25p80 spi0.1: mx25l12805d (16384 Kbytes)
[    3.696000] 9 cmdlinepart partitions found on MTD device m25p80
[    3.702000] Creating 9 MTD partitions on "m25p80":
[    3.707000] 0x000000000000-0x000000040000 : "loader1"
[    3.770000] 0x000000040000-0x000000400000 : "boot1"
[    3.812000] 0x000000400000-0x000000440000 : "loader2"
[    3.882000] 0x000000440000-0x000000800000 : "boot2"
[    3.946000] 0x000000800000-0x000000880000 : "rsvd"
[    4.015000] 0x000000880000-0x000000e80000 : "bootubi"
[    4.084000] 0x000000e80000-0x000000ec0000 : "conf"
[    4.147000] 0x000000ec0000-0x000000fc0000 : "stackconf"
[    4.217000] 0x000000fc0000-0x000001000000 : "syslog"
[    4.300000] ONFI flash detected
[    4.303000] ONFI param page 0 valid
[    4.307000] NAND device: Manufacturer ID: 0x2c, Chip ID: 0xf1 (Micron MT29F1G08ABADAWP)
[    4.320000] Scanning device for bad blocks
[    4.550000] UBI: attaching mtd5 to ubi0
[    4.564000] UBI: physical eraseblock size:   4096 bytes (4 KiB)
[    4.570000] UBI: logical eraseblock size:    3968 bytes
[    4.575000] UBI: smallest flash I/O unit:    1
[    4.580000] UBI: VID header offset:          64 (aligned 64)
[    4.585000] UBI: data offset:                128
[    5.586000] UBI: max. sequence number:       2
[    5.629000] UBI: attached mtd5 to ubi0
[    5.633000] UBI: MTD device name:            "bootubi"
[    5.638000] UBI: MTD device size:            6 MiB
[    5.643000] UBI: number of good PEBs:        1536
[    5.647000] UBI: number of bad PEBs:         0
[    5.652000] UBI: number of corrupted PEBs:   0
[    5.656000] UBI: max. allowed volumes:       23
[    5.661000] UBI: wear-leveling threshold:    4096
[    5.666000] UBI: number of internal volumes: 1
[    5.670000] UBI: number of user volumes:     0
[    5.675000] UBI: available PEBs:             1532
[    5.679000] UBI: total number of reserved PEBs: 4
[    5.684000] UBI: number of PEBs reserved for bad PEB handling: 0
[    5.690000] UBI: max/mean erase counter: 2/1
[    5.694000] UBI: image sequence number:  -2100605408
[    5.699000] UBI: background thread "ubi_bgt0d" started, PID 220
[    5.716000] UBI: attaching mtd9 to ubi1
[    5.721000] UBI: physical eraseblock size:   131072 bytes (128 KiB)
[    5.727000] UBI: logical eraseblock size:    129024 bytes
[    5.732000] UBI: smallest flash I/O unit:    2048
[    5.737000] UBI: sub-page size:              512
[    5.742000] UBI: VID header offset:          512 (aligned 512)
[    5.748000] UBI: data offset:                2048
[    6.480000] UBI: max. sequence number:       1480554
[    6.556000] UBI: attached mtd9 to ubi1
[    6.560000] UBI: MTD device name:            "gen_nand.0"
[    6.566000] UBI: MTD device size:            128 MiB
[    6.571000] UBI: number of good PEBs:        1024
[    6.575000] UBI: number of bad PEBs:         0
[    6.580000] UBI: number of corrupted PEBs:   0
[    6.584000] UBI: max. allowed volumes:       128
[    6.589000] UBI: wear-leveling threshold:    4096
[    6.594000] UBI: number of internal volumes: 1
[    6.598000] UBI: number of user volumes:     7
[    6.603000] UBI: available PEBs:             514
[    6.607000] UBI: total number of reserved PEBs: 510
[    6.612000] UBI: number of PEBs reserved for bad PEB handling: 20
[    6.618000] UBI: max/mean erase counter: 1562/1446
[    6.623000] UBI: image sequence number:  1648387176
[    6.629000] UBI: background thread "ubi_bgt1d" started, PID 231
[    7.064000] tun: Universal TUN/TAP device driver, 1.6
[    7.069000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    7.163000] i2c /dev entries driver
[    7.263000] TCP cubic registered
[    7.266000] Initializing XFRM netlink socket
[    7.271000] NET: Registered protocol family 17
[    7.275000] NET: Registered protocol family 15
[    7.280000] 802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
[    7.287000] All bugs added by David S. Miller <davem@redhat.com>
[    7.293000] Meraki MS22 or MS220-24 board detected
[    7.442000] i2c-gpio i2c-gpio.1: using pins 10 (SDA) and 11 (SCL)
[    7.462000] at24 1-0051: 8192 byte at24 EEPROM (writable)
[    7.630000] meraki-config: Failure to read from eeprom
[    8.778000] i2c-gpio i2c-gpio.2: using pins 79 (SDA) and 80 (SCL)
[    8.828000] devtmpfs: mounted
[    9.004000] Freeing unused kernel memory: 10172k freed
[    9.060000] Made it into bootsh: Sep  4 2015 14:12:07
[    9.065000] bootsh build switch-5-176388
[    9.106000] mount_bootpartition: mounting bootroot: No such file or directory
grep meraki-board-config /proc/misc | awk '{print $1}'
[    9.140000] unmount_bootpartition: unmounting bootroot: No such file or directory
[    9.441000] UBIFS: mounted UBI device 1, volume 4, name "storage"
[    9.447000] UBIFS: file system size:   7354368 bytes (7182 KiB, 7 MiB, 57 LEBs)
[    9.455000] UBIFS: journal size:       1032193 bytes (1008 KiB, 0 MiB, 6 LEBs)
[    9.462000] UBIFS: media format:       w4/r0 (latest is w4/r0)
[    9.468000] UBIFS: default compressor: lzo
[    9.472000] UBIFS: reserved for root:  347364 bytes (339 KiB)
[    9.630000] init started: BusyBox v1.20.2 (2015-09-04 13:48:08 PDT)
[    9.851000] ln: /dev/board-config: File exists
WARNING! THIS CONSOLE IS LOGGED! UNAUTHORIZED ACCESS FORBIDDEN!
<Meraki> [   10.337000] sysctl: error: 'vm.extfrag_threshold' is an unknown key
[   10.491000] sh: write error: Device or resource busy
[   11.472000] switch: 'Meraki MS22/MS220-24' board detected
[   11.478000] vtss_phy_chip_temp_init_private:7060 Temperature reading not supported for family: None
[   11.861000] mknod: /dev/switch: File exists
[   12.369000] sysctl -w vm.panic_on_oom=2
[   12.388000] vm.panic_on_oom = 2
[   18.228000] click: starting router thread pid 676 (86e17880)
[   23.937000] Single synchronous check for reset
[   24.400000] pd690xx 2-0030: pd690xx_read_value: i2c_transfer[30:031a] returned -6
[   24.449000] pd690xx 2-0030: pd690xx_read_value: i2c_transfer[30:031a] returned -6
[   25.505000] 
[   25.530000] boot 64 build switch-5-176388 board elemental mac 00:18:0A:53:EC:7F
[   25.554000] Module: vtss_core  .text=0xc1483000 .data=0xc1504ce0 .bss=0xc1505070
[   25.554000] Module: vtss_ioctl  .text=0xc162f000 .data=0xc163cf70 .bss=0xc163d140
[   25.554000] Module: proclikefs  .text=0xc10fd000 .data= .bss=0xc10fdee0
[   25.554000] Module: merakiclick  .text=0xc1897000 .data=0xc199c490 .bss=0xc199c6e0
[   25.554000] Module: elts_meraki  .text=0xc1d79000 .data=0xc1eef590 .bss=0xc1eefcd0
[   25.554000] Module: pd690xx_poe  .text=0xc1ff6000 .data=0xc1ff8370 .bss=
[   25.554000] Module: vc_click  .text=0xc205d000 .data=0xc2087ad0 .bss=0xc2087cb0
[   25.682000] phram: phram-oops device: 0x10000 at 0x7ff0000
[   32.179000] chatter: from_sw0 :: FromVitesse: initializing fdma
[   36.334000] ethernet_port wired0, ip 192.168.100.241, netmask 255.255.255.0, gw 192.168.100.1, mtu 1500, bcast 192.168.100.255, dns1 192.168.100.1, is_static true, vid 1, static_ip_failover false, dhcp_vlan_failover false

<Meraki> [   49.562000] ethernet_port wired0, ip 0.0.0.0, netmask 0.0.0.0, gw 0.0.0.0, mtu 0, bcast 0.0.0.0, dns1 0.0.0.0, vid 0, static_ip_failover false, dhcp_vlan_failover false
[   50.196000] 
[   50.196000] !!!!! {/usr/bin/fastcgi} reading /click/scan_aggregator/json failed [2]: No such file or directory
[   52.791000] ethernet_port wired0, ip 192.168.100.193, netmask 255.255.255.0, gw 192.168.100.1, mtu 1500, bcast 192.168.100.255, dns1 192.168.100.1, vid 1, static_ip_failover false, dhcp_vlan_failover false

<Meraki> [  107.270000] 
[  107.270000] !!!!! {/usr/bin/config_updater} starting upgrade to version "switch-14-202011050545-Gae67aced-rel-keyboard"
[  121.117000] UBI: scrubbed PEB 669 (LEB 3:2), data moved to PEB 542
[  122.714000] UBI: scrubbed PEB 693 (LEB 3:17), data moved to PEB 535
[  124.823000] UBI: scrubbed PEB 744 (LEB 3:33), data moved to PEB 531

<Meraki>

**Comment by halmartin** [comment]
Thanks for confirming the UART header and providing your boot log.

Is it possible to get a photo of the whole board mounted inside the chassis? Then I can annotate the board photo and add it to the installation doc.

For example, this is the internals of the MS220-24P with the SOIC16 highlighted:
![MS220-24-SOIC](https://user-images.githubusercontent.com/1230969/99917316-c357c280-2d0f-11eb-822f-251e547d7906.jpg)

**Comment by networkdawg** [comment]
@halmartin I have added a few more photos in my album shared above. I believe the SOIC16 is right beside the right hand heat sink.

**Comment by halmartin** [comment]
Thanks! I've added the MS22P to the installation instructions.
