### ISSUE TITLE
Interface lights not working on luton-based switches

### ISSUE THREAD

**Issue by chris3453** [halmartin/meraki-builder#16]
Interface LEDs don't working when using the following version: `postmerkOS-20210424`

Interfaces do however pass traffic and POE power without issue.

**Comment by halmartin** [comment]
This is a known issue. I'm not sure how the port LEDs are controlled on `luton`, as there isn't any GPIO configuration in the Meraki initscripts for this (that I can find) and the port LEDs work on the `jaguar_dual` switches (`-48`)

In the mean time, you can run `cat /click/switch_port_table/dump_pports` to get a summary of the port status.

**Comment by rob235** [comment]
I've just flashed an MS220-24P with postmerkOS-20210424 and noticed also that the interface LED's aren't working. Passing traffic and POE are fine though.

**Comment by halmartin** [comment]
@rob235 thanks for the report, it appears the issue is with all luton-based switches. I changed the issue title to reflect this.

**Comment by halmartin** [comment]
Can you tell me if the following command enables link lights on your switch?
```
echo link > /click/sw0_ctrl/led_mode
```

It works on my MS220-8P, but I don't have an MS220-24 to test.

**Comment by xoy74** [comment]
> Can you tell me if the following command enables link lights on your switch?
> 
> ```
> echo link > /click/sw0_ctrl/led_mode
> ```
> It works on my MS220-8P, but I don't have an MS220-24 to test.

Amazong, this works on my MS220-8P that I've been using without status lights for about 2 years. Is there a similar command to enable the speed LEDs as well ?

**Comment by halmartin** [comment]
> Is there a similar command to enable the speed LEDs as well ?

The first LED is used to indicate link, and the second LED is used to indicate PoE status:
![Screenshot 2023-04-05 07 07 54](https://user-images.githubusercontent.com/1230969/229986311-c9fa8cfc-8f31-4c29-9197-bb95a4c962bb.png)

The switch has no ability to indicate the speed of the link via LEDs.

**Comment by xoy74** [comment]
Thank you, appreciate it.
