### ISSUE TITLE
initialize poe before network

### ISSUE THREAD

**Issue by hall** [halmartin/meraki-builder#30]
The DHCP server on my network is powered by postmerkOS. As it stands, during boot, the switch [waits for an address](https://github.com/halmartin/meraki-builder/blob/f736e344d541be6961d9de37dd36224d40b55070/buildroot/board/meraki/ms220/overlay/etc/init.d/S10clickconfig#L206-L223) prior to [initializing PoE](https://github.com/halmartin/meraki-builder/blob/f736e344d541be6961d9de37dd36224d40b55070/buildroot/board/meraki/ms220/overlay/etc/init.d/S11poe). Thus it will always fail and fallback to the hardcoded address.

As someone with very little knowledge here, is there any reason you're aware of that the order cannot be flipped? I'm happy to test suggested approaches -- just didn't want to break things (on my only device) if it was a lost cause.

**Comment by halmartin** [comment]
> is there any reason you're aware of that the order cannot be flipped

Providing PoE power before completing data plane configuration would completely break the security boundary provided by VLANs. PoE initialisation must happen after we configure the data plane in `click` (which also starts DHCP). As far as I know, this is also the order of operations from the Meraki firmware.

Therefore, it is not advised to have your DHCP server powered directly from the switch, as you will encounter this issue.

If you need PoE to start earlier in your network, `/etc` is on a writable overlay, rename `S11poe` to run before `S10clickconfig` and you'll have PoE before DHCP.

**Comment by hall** [comment]
> break the security boundary provided by VLANs

Ah, it would have taken me quite a bit of time to come to that conclusion!

Thanks for the explanation _and_ a workaround. I'll probably move that device off PoE again now that I know it's done this way intentionally.
