### ISSUE TITLE
Docker image ubuntu1804-buildroot does not exist for MX80 build

### ISSUE THREAD

**Issue by appleeimac** [halmartin/meraki-builder#33]
MX80 buld script complains that "Ubuntu1804-buildroot:latest" isn't found.

**Comment by halmartin** [comment]
Run `cd docker/mx80 && make` and if you receive an error, please paste the _entire_ output from your terminal, including the commands used that lead up to the error.

**Comment by halmartin** [comment]
Please re-open this if you still have issues building the MX80 image.

**Comment by appleeimac** [comment]
I haven't had a chance to check this.
________________________________

**Comment by appleeimac** [comment]
Ubuntu 18.04-23.04 complain that Docker is "Unable to find image "ubuntu1804-buildroot:latest' locally and pull access is denied" when running make docker build in the Docker/MX80 directory

**Comment by halmartin** [comment]
I am unable to help you with these generic descriptions of the problem.

> please paste the entire output from your terminal, including the commands used that lead up to the error.

**Comment by appleeimac** [comment]
![image](https://github.com/halmartin/meraki-builder/assets/125357488/8c0ea3f9-f91d-4fef-9318-31d97026919e) Hope this helps more, not sure how better to describe it.

**Comment by halmartin** [comment]
Run the following commands:
```
make docker-image
make docker-build
```

The docker image is built by `make docker-image` and the buildroot image is built by `make docker-build`

This would have worked if you had just run `make` in the directory, [as I stated previously on June 16](https://github.com/halmartin/meraki-builder/issues/33#issuecomment-1594287733).

**Comment by appleeimac** [comment]
I'm just using the instructions on the readme.
________________________________
